// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Ethernet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EthernetStatus struct {
	_tab flatbuffers.Table
}

func GetRootAsEthernetStatus(buf []byte, offset flatbuffers.UOffsetT) *EthernetStatus {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EthernetStatus{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsEthernetStatus(buf []byte, offset flatbuffers.UOffsetT) *EthernetStatus {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EthernetStatus{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *EthernetStatus) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EthernetStatus) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EthernetStatus) Sync() BusSync {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return BusSync(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *EthernetStatus) MutateSync(n BusSync) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func EthernetStatusStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func EthernetStatusAddSync(builder *flatbuffers.Builder, sync BusSync) {
	builder.PrependInt8Slot(0, int8(sync), 0)
}
func EthernetStatusEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
