// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FlexRay

import "strconv"

type BufferDirection int8

const (
	BufferDirectionTx BufferDirection = 0
	BufferDirectionRx BufferDirection = 1
)

var EnumNamesBufferDirection = map[BufferDirection]string{
	BufferDirectionTx: "Tx",
	BufferDirectionRx: "Rx",
}

var EnumValuesBufferDirection = map[string]BufferDirection{
	"Tx": BufferDirectionTx,
	"Rx": BufferDirectionRx,
}

func (v BufferDirection) String() string {
	if s, ok := EnumNamesBufferDirection[v]; ok {
		return s
	}
	return "BufferDirection(" + strconv.FormatInt(int64(v), 10) + ")"
}
