// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FlexRay

import "strconv"

type BusSync int8

const (
	BusSyncNoSync BusSync = 0
	BusSyncSync   BusSync = 1
)

var EnumNamesBusSync = map[BusSync]string{
	BusSyncNoSync: "NoSync",
	BusSyncSync:   "Sync",
}

var EnumValuesBusSync = map[string]BusSync{
	"NoSync": BusSyncNoSync,
	"Sync":   BusSyncSync,
}

func (v BusSync) String() string {
	if s, ok := EnumNamesBusSync[v]; ok {
		return s
	}
	return "BusSync(" + strconv.FormatInt(int64(v), 10) + ")"
}
