// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FlexRay

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FlexrayStatus struct {
	_tab flatbuffers.Table
}

func GetRootAsFlexrayStatus(buf []byte, offset flatbuffers.UOffsetT) *FlexrayStatus {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FlexrayStatus{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFlexrayStatus(buf []byte, offset flatbuffers.UOffsetT) *FlexrayStatus {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FlexrayStatus{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *FlexrayStatus) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FlexrayStatus) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FlexrayStatus) Sync() BusSync {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return BusSync(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *FlexrayStatus) MutateSync(n BusSync) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func FlexrayStatusStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FlexrayStatusAddSync(builder *flatbuffers.Builder, sync BusSync) {
	builder.PrependInt8Slot(0, int8(sync), 0)
}
func FlexrayStatusEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
