// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FlexRay

import "strconv"

type FrameIndicatorBits byte

const (
	FrameIndicatorBitsStartup  FrameIndicatorBits = 1
	FrameIndicatorBitsSync     FrameIndicatorBits = 2
	FrameIndicatorBitsNotNull  FrameIndicatorBits = 4
	FrameIndicatorBitsPayload  FrameIndicatorBits = 8
	FrameIndicatorBitsReserved FrameIndicatorBits = 16
)

var EnumNamesFrameIndicatorBits = map[FrameIndicatorBits]string{
	FrameIndicatorBitsStartup:  "Startup",
	FrameIndicatorBitsSync:     "Sync",
	FrameIndicatorBitsNotNull:  "NotNull",
	FrameIndicatorBitsPayload:  "Payload",
	FrameIndicatorBitsReserved: "Reserved",
}

var EnumValuesFrameIndicatorBits = map[string]FrameIndicatorBits{
	"Startup":  FrameIndicatorBitsStartup,
	"Sync":     FrameIndicatorBitsSync,
	"NotNull":  FrameIndicatorBitsNotNull,
	"Payload":  FrameIndicatorBitsPayload,
	"Reserved": FrameIndicatorBitsReserved,
}

func (v FrameIndicatorBits) String() string {
	if s, ok := EnumNamesFrameIndicatorBits[v]; ok {
		return s
	}
	return "FrameIndicatorBits(" + strconv.FormatInt(int64(v), 10) + ")"
}
