// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FlexRay

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimeSpec struct {
	_tab flatbuffers.Struct
}

func (rcv *TimeSpec) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimeSpec) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *TimeSpec) Psec10() int64 {
	return rcv._tab.GetInt64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *TimeSpec) MutatePsec10(n int64) bool {
	return rcv._tab.MutateInt64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateTimeSpec(builder *flatbuffers.Builder, psec10 int64) flatbuffers.UOffsetT {
	builder.Prep(8, 8)
	builder.PrependInt64(psec10)
	return builder.Offset()
}
