---
version: '3'

metadata:
  package:
    download: '{{.REPO}}/releases/download/v{{.TAG}}/ModelC-{{.TAG}}-{{.PLATFORM_ARCH}}.zip'

  container:
    repository: ghcr.io/boschglobal/dse-modelc

  models:
    dse.modelc.csv:
      name: csv
      displayName: dse.modelc.csv
      path: examples/csv
      workflows: []
      platforms:
        - linux-amd64
        - linux-x86
        - linux-i386
        - windows-x64
        - windows-x86
      channels:
        - alias: signal_channel

vars:
  # When running from E2E tests (i.e. Docker in Docker), the ENTRYDIR (for
  # Docker commands) must be set to the host relative path.
  ENTRYDIR: '{{if .SIM}}{{.ENTRYWORKDIR}}/{{.SIM}}{{else}}{{.PWD}}{{end}}'
  # Container image specification.
  MODELC_IMAGE: '{{.MODELC_IMAGE | default "ghcr.io/boschglobal/dse-modelc"}}'
  IMAGE_TAG: '{{if .MODELC_TAG}}{{.MODELC_TAG}}{{else}}{{if .IMAGE_TAG}}{{.IMAGE_TAG}}{{else}}latest{{end}}{{end}}'

tasks:

  info:
    run: always
    dir: '{{.USER_WORKING_DIR}}'
    label: dse:modelc:info
    cmds:
      - echo "{{.ENTRYDIR}}"
      - echo "{{.MODELC_IMAGE}}"
      - echo "{{.IMAGE_TAG}}"
