// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Channel

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChannelMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsChannelMessage(buf []byte, offset flatbuffers.UOffsetT) *ChannelMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChannelMessage{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsChannelMessage(buf []byte, offset flatbuffers.UOffsetT) *ChannelMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChannelMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ChannelMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChannelMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChannelMessage) ModelUid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChannelMessage) MutateModelUid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *ChannelMessage) MessageType() MessageType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return MessageType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ChannelMessage) MutateMessageType(n MessageType) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *ChannelMessage) Message(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func (rcv *ChannelMessage) ControlCode() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChannelMessage) MutateControlCode(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *ChannelMessage) Token() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChannelMessage) MutateToken(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *ChannelMessage) Rc() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChannelMessage) MutateRc(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func (rcv *ChannelMessage) Response() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ChannelMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func ChannelMessageAddModelUid(builder *flatbuffers.Builder, modelUid uint32) {
	builder.PrependUint32Slot(0, modelUid, 0)
}
func ChannelMessageAddMessageType(builder *flatbuffers.Builder, messageType MessageType) {
	builder.PrependByteSlot(1, byte(messageType), 0)
}
func ChannelMessageAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(message), 0)
}
func ChannelMessageAddControlCode(builder *flatbuffers.Builder, controlCode uint32) {
	builder.PrependUint32Slot(3, controlCode, 0)
}
func ChannelMessageAddToken(builder *flatbuffers.Builder, token int32) {
	builder.PrependInt32Slot(4, token, 0)
}
func ChannelMessageAddRc(builder *flatbuffers.Builder, rc int32) {
	builder.PrependInt32Slot(5, rc, 0)
}
func ChannelMessageAddResponse(builder *flatbuffers.Builder, response flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(response), 0)
}
func ChannelMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
