// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Channel

import "strconv"

type MessageType byte

const (
	MessageTypeNONE        MessageType = 0
	MessageTypeSignalWrite MessageType = 1
	MessageTypeSignalRead  MessageType = 2
	MessageTypeSignalValue MessageType = 3
	MessageTypeSignalIndex MessageType = 4
)

var EnumNamesMessageType = map[MessageType]string{
	MessageTypeNONE:        "NONE",
	MessageTypeSignalWrite: "SignalWrite",
	MessageTypeSignalRead:  "SignalRead",
	MessageTypeSignalValue: "SignalValue",
	MessageTypeSignalIndex: "SignalIndex",
}

var EnumValuesMessageType = map[string]MessageType{
	"NONE":        MessageTypeNONE,
	"SignalWrite": MessageTypeSignalWrite,
	"SignalRead":  MessageTypeSignalRead,
	"SignalValue": MessageTypeSignalValue,
	"SignalIndex": MessageTypeSignalIndex,
}

func (v MessageType) String() string {
	if s, ok := EnumNamesMessageType[v]; ok {
		return s
	}
	return "MessageType(" + strconv.FormatInt(int64(v), 10) + ")"
}
