// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Channel

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SignalIndex struct {
	_tab flatbuffers.Table
}

func GetRootAsSignalIndex(buf []byte, offset flatbuffers.UOffsetT) *SignalIndex {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SignalIndex{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSignalIndex(buf []byte, offset flatbuffers.UOffsetT) *SignalIndex {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SignalIndex{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SignalIndex) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SignalIndex) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SignalIndex) Indexes(obj *SignalLookup, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SignalIndex) IndexesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SignalIndexStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SignalIndexAddIndexes(builder *flatbuffers.Builder, indexes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(indexes), 0)
}
func SignalIndexStartIndexesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SignalIndexEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
