// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Frame

import "strconv"

type CanFrameType int8

const (
	CanFrameTypeBaseFrame       CanFrameType = 0
	CanFrameTypeExtendedFrame   CanFrameType = 1
	CanFrameTypeFdBaseFrame     CanFrameType = 2
	CanFrameTypeFdExtendedFrame CanFrameType = 3
)

var EnumNamesCanFrameType = map[CanFrameType]string{
	CanFrameTypeBaseFrame:       "BaseFrame",
	CanFrameTypeExtendedFrame:   "ExtendedFrame",
	CanFrameTypeFdBaseFrame:     "FdBaseFrame",
	CanFrameTypeFdExtendedFrame: "FdExtendedFrame",
}

var EnumValuesCanFrameType = map[string]CanFrameType{
	"BaseFrame":       CanFrameTypeBaseFrame,
	"ExtendedFrame":   CanFrameTypeExtendedFrame,
	"FdBaseFrame":     CanFrameTypeFdBaseFrame,
	"FdExtendedFrame": CanFrameTypeFdExtendedFrame,
}

func (v CanFrameType) String() string {
	if s, ok := EnumNamesCanFrameType[v]; ok {
		return s
	}
	return "CanFrameType(" + strconv.FormatInt(int64(v), 10) + ")"
}
