// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Frame

import "strconv"

type FrameTypes byte

const (
	FrameTypesNONE     FrameTypes = 0
	FrameTypesCanFrame FrameTypes = 1
)

var EnumNamesFrameTypes = map[FrameTypes]string{
	FrameTypesNONE:     "NONE",
	FrameTypesCanFrame: "CanFrame",
}

var EnumValuesFrameTypes = map[string]FrameTypes{
	"NONE":     FrameTypesNONE,
	"CanFrame": FrameTypesCanFrame,
}

func (v FrameTypes) String() string {
	if s, ok := EnumNamesFrameTypes[v]; ok {
		return s
	}
	return "FrameTypes(" + strconv.FormatInt(int64(v), 10) + ")"
}
