// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Frame

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Timing struct {
	_tab flatbuffers.Table
}

func GetRootAsTiming(buf []byte, offset flatbuffers.UOffsetT) *Timing {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Timing{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTiming(buf []byte, offset flatbuffers.UOffsetT) *Timing {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Timing{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Timing) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Timing) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Timing) Send() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Timing) MutateSend(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *Timing) Arbitration() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Timing) MutateArbitration(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *Timing) Recv() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Timing) MutateRecv(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func TimingStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TimingAddSend(builder *flatbuffers.Builder, send int64) {
	builder.PrependInt64Slot(0, send, 0)
}
func TimingAddArbitration(builder *flatbuffers.Builder, arbitration int64) {
	builder.PrependInt64Slot(1, arbitration, 0)
}
func TimingAddRecv(builder *flatbuffers.Builder, recv int64) {
	builder.PrependInt64Slot(2, recv, 0)
}
func TimingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
