// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Can

import "strconv"

type BufferStatus int8

const (
	BufferStatusNone    BufferStatus = 0
	BufferStatusRxError BufferStatus = 1
)

var EnumNamesBufferStatus = map[BufferStatus]string{
	BufferStatusNone:    "None",
	BufferStatusRxError: "RxError",
}

var EnumValuesBufferStatus = map[string]BufferStatus{
	"None":    BufferStatusNone,
	"RxError": BufferStatusRxError,
}

func (v BufferStatus) String() string {
	if s, ok := EnumNamesBufferStatus[v]; ok {
		return s
	}
	return "BufferStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
