// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Can

import "strconv"

type BusState int8

const (
	BusStateBusOff BusState = 0
	BusStateIdle   BusState = 1
	BusStateSync   BusState = 2
)

var EnumNamesBusState = map[BusState]string{
	BusStateBusOff: "BusOff",
	BusStateIdle:   "Idle",
	BusStateSync:   "Sync",
}

var EnumValuesBusState = map[string]BusState{
	"BusOff": BusStateBusOff,
	"Idle":   BusStateIdle,
	"Sync":   BusStateSync,
}

func (v BusState) String() string {
	if s, ok := EnumNamesBusState[v]; ok {
		return s
	}
	return "BusState(" + strconv.FormatInt(int64(v), 10) + ")"
}
