// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Can

import "strconv"

type FrameType int8

const (
	FrameTypeStandardFrame FrameType = 0
	FrameTypeExtendedFrame FrameType = 1
)

var EnumNamesFrameType = map[FrameType]string{
	FrameTypeStandardFrame: "StandardFrame",
	FrameTypeExtendedFrame: "ExtendedFrame",
}

var EnumValuesFrameType = map[string]FrameType{
	"StandardFrame": FrameTypeStandardFrame,
	"ExtendedFrame": FrameTypeExtendedFrame,
}

func (v FrameType) String() string {
	if s, ok := EnumNamesFrameType[v]; ok {
		return s
	}
	return "FrameType(" + strconv.FormatInt(int64(v), 10) + ")"
}
