// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Pdu

import "strconv"

type CanFrameType int8

const (
	/// CAN Data Frame.
	CanFrameTypeDataFrame CanFrameType = 0
	/// CAN Remote Frame.
	CanFrameTypeRemoteFrame CanFrameType = 1
	/// CAN Error Frame.
	CanFrameTypeErrorFrame CanFrameType = 2
	/// CAN Overload Frame.
	CanFrameTypeOverloadFrame CanFrameType = 3
)

var EnumNamesCanFrameType = map[CanFrameType]string{
	CanFrameTypeDataFrame:     "DataFrame",
	CanFrameTypeRemoteFrame:   "RemoteFrame",
	CanFrameTypeErrorFrame:    "ErrorFrame",
	CanFrameTypeOverloadFrame: "OverloadFrame",
}

var EnumValuesCanFrameType = map[string]CanFrameType{
	"DataFrame":     CanFrameTypeDataFrame,
	"RemoteFrame":   CanFrameTypeRemoteFrame,
	"ErrorFrame":    CanFrameTypeErrorFrame,
	"OverloadFrame": CanFrameTypeOverloadFrame,
}

func (v CanFrameType) String() string {
	if s, ok := EnumNamesCanFrameType[v]; ok {
		return s
	}
	return "CanFrameType(" + strconv.FormatInt(int64(v), 10) + ")"
}
