// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Pdu

import "strconv"

type CanMessageFormat int8

const (
	/// CAN Base Format (pdu.id is 11-bits).
	CanMessageFormatBaseFrameFormat CanMessageFormat = 0
	/// CAN Extended Format (pdu.id is 29-bits).
	CanMessageFormatExtendedFrameFormat CanMessageFormat = 1
	/// CAN FD Base Format (pdu.id is 11-bits).
	CanMessageFormatFdBaseFrameFormat CanMessageFormat = 2
	/// CAN FD Extended Format (pdu.id is 29-bits).
	CanMessageFormatFdExtendedFrameFormat CanMessageFormat = 3
)

var EnumNamesCanMessageFormat = map[CanMessageFormat]string{
	CanMessageFormatBaseFrameFormat:       "BaseFrameFormat",
	CanMessageFormatExtendedFrameFormat:   "ExtendedFrameFormat",
	CanMessageFormatFdBaseFrameFormat:     "FdBaseFrameFormat",
	CanMessageFormatFdExtendedFrameFormat: "FdExtendedFrameFormat",
}

var EnumValuesCanMessageFormat = map[string]CanMessageFormat{
	"BaseFrameFormat":       CanMessageFormatBaseFrameFormat,
	"ExtendedFrameFormat":   CanMessageFormatExtendedFrameFormat,
	"FdBaseFrameFormat":     CanMessageFormatFdBaseFrameFormat,
	"FdExtendedFrameFormat": CanMessageFormatFdExtendedFrameFormat,
}

func (v CanMessageFormat) String() string {
	if s, ok := EnumNamesCanMessageFormat[v]; ok {
		return s
	}
	return "CanMessageFormat(" + strconv.FormatInt(int64(v), 10) + ")"
}
