// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Pdu

import "strconv"

type IpAddr byte

const (
	IpAddrNONE IpAddr = 0
	IpAddrv4   IpAddr = 1
	IpAddrv6   IpAddr = 2
)

var EnumNamesIpAddr = map[IpAddr]string{
	IpAddrNONE: "NONE",
	IpAddrv4:   "v4",
	IpAddrv6:   "v6",
}

var EnumValuesIpAddr = map[string]IpAddr{
	"NONE": IpAddrNONE,
	"v4":   IpAddrv4,
	"v6":   IpAddrv6,
}

func (v IpAddr) String() string {
	if s, ok := EnumNamesIpAddr[v]; ok {
		return s
	}
	return "IpAddr(" + strconv.FormatInt(int64(v), 10) + ")"
}
