// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Pdu

import "strconv"

type IpProtocol byte

const (
	IpProtocolNone IpProtocol = 0
	IpProtocolTcp  IpProtocol = 6
	IpProtocolUdp  IpProtocol = 17
)

var EnumNamesIpProtocol = map[IpProtocol]string{
	IpProtocolNone: "None",
	IpProtocolTcp:  "Tcp",
	IpProtocolUdp:  "Udp",
}

var EnumValuesIpProtocol = map[string]IpProtocol{
	"None": IpProtocolNone,
	"Tcp":  IpProtocolTcp,
	"Udp":  IpProtocolUdp,
}

func (v IpProtocol) String() string {
	if s, ok := EnumNamesIpProtocol[v]; ok {
		return s
	}
	return "IpProtocol(" + strconv.FormatInt(int64(v), 10) + ")"
}
