// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Pdu

import "strconv"

type SocketAdapter byte

const (
	SocketAdapterNONE SocketAdapter = 0
	/// DoIp: Diagnostic Communication over Internet Protocol.
	SocketAdapterdo_ip SocketAdapter = 1
	/// Some/IP: Scalable service-Oriented Midedleware over IP.
	SocketAdaptersome_ip SocketAdapter = 2
)

var EnumNamesSocketAdapter = map[SocketAdapter]string{
	SocketAdapterNONE:    "NONE",
	SocketAdapterdo_ip:   "do_ip",
	SocketAdaptersome_ip: "some_ip",
}

var EnumValuesSocketAdapter = map[string]SocketAdapter{
	"NONE":    SocketAdapterNONE,
	"do_ip":   SocketAdapterdo_ip,
	"some_ip": SocketAdaptersome_ip,
}

func (v SocketAdapter) String() string {
	if s, ok := EnumNamesSocketAdapter[v]; ok {
		return s
	}
	return "SocketAdapter(" + strconv.FormatInt(int64(v), 10) + ")"
}
