// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Pdu

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Stream struct {
	_tab flatbuffers.Table
}

func GetRootAsStream(buf []byte, offset flatbuffers.UOffsetT) *Stream {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Stream{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsStream(buf []byte, offset flatbuffers.UOffsetT) *Stream {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Stream{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Stream) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Stream) Table() flatbuffers.Table {
	return rcv._tab
}

// / STREAM: PDU Vector.
func (rcv *Stream) Pdus(obj *Pdu, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Stream) PdusLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

// / STREAM: PDU Vector.
// / Metadata: Node UID of the Simulation (or System) node which is sending
// /  this stream object. Used by a Node to detect incomming stream objects
// /  which the Node had previously sent (i.e. an echo from the underlying
// /  implementation of the stream transport).
func (rcv *Stream) NodeUid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

// / Metadata: Node UID of the Simulation (or System) node which is sending
// /  this stream object. Used by a Node to detect incomming stream objects
// /  which the Node had previously sent (i.e. an echo from the underlying
// /  implementation of the stream transport).
func (rcv *Stream) MutateNodeUid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func StreamStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StreamAddPdus(builder *flatbuffers.Builder, pdus flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(pdus), 0)
}
func StreamStartPdusVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StreamAddNodeUid(builder *flatbuffers.Builder, nodeUid uint32) {
	builder.PrependUint32Slot(1, nodeUid, 0)
}
func StreamEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
