---
name: Redis

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # Once a month.

permissions:
  contents: read

jobs:
  redis-server:
    runs-on: ubuntu-latest
    env:
      REDIS_WIN_VERSION: 7.2.13

    steps:
      - name: Get Redis ${{ env.REDIS_WIN_VERSION }} release from redis-windows/redis-windows
        id: get-release
        run: |
          RELEASE_DATA=$(curl -s https://api.github.com/repos/redis-windows/redis-windows/releases/tags/${REDIS_WIN_VERSION})
          DOWNLOAD_URL=$(echo "$RELEASE_DATA" | jq -r '.assets[] | select(.name | test("Redis-.*-Windows-x64-msys2\\.zip")) | .browser_download_url')
          echo "download_url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT

      - name: Download Redis Windows package
        run: |
          curl -L -o redis-windows.zip "${{ steps.get-release.outputs.download_url }}"
          unzip redis-windows.zip
          mkdir -p redis-windows
          topdir=$(unzip -Z1 redis-windows.zip | head -1 | cut -d/ -f1)
          rsync -a "${topdir}/" redis-windows/
          rm -rf "$topdir"
          ls -l redis-windows

      - name: Upload redis-server as artifact
        uses: actions/upload-artifact@v4
        with:
          name: redis-server-windows
          path: |
            redis-windows/redis-server.exe
            redis-windows/*.dll
          retention-days: 90  # Adjust as needed
          if-no-files-found: error
